[Link](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud/code?datasetId=310&sortBy=voteCount) dos dados

## Lendo e analisando a base de dados:

In [1]:
import pandas as pd

credit_card = pd.read_csv('../dados/creditcard.csv', nrows=int(284807*0.1))
credit_card.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [2]:
credit_card.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [35]:
credit_card[credit_card['Class'] == 1]

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,406,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
623,472,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
4920,4462,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
6108,6986,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
6329,7519,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26802,34256,0.539276,1.554890,-2.066180,3.241617,0.184736,0.028330,-1.515521,0.537035,-1.999846,...,0.371773,0.111955,-0.305225,-1.053835,0.771175,0.240878,0.418435,0.232170,19.02,1
27362,34521,1.081234,0.416414,0.862919,2.520863,-0.005021,0.563341,-0.123372,0.223122,-0.673598,...,-0.159387,-0.305154,0.053620,0.011761,0.375146,-0.106299,0.021008,0.010559,1.52,1
27627,34634,0.333499,1.699873,-2.596561,3.643945,-0.585068,-0.654659,-2.275789,0.675229,-2.042416,...,0.469212,-0.144363,-0.317981,-0.769644,0.807855,0.228164,0.551002,0.305473,18.96,1
27738,34684,-2.439237,2.591458,-2.840126,1.286244,-1.777016,-1.436139,-2.206056,-2.282725,-0.292885,...,1.774460,-0.771390,0.065727,0.103916,-0.057578,0.242652,-0.268649,-0.743713,125.30,1
27749,34687,-0.860827,3.131790,-5.052968,5.420941,-2.494141,-1.811287,-5.479117,1.189472,-3.908206,...,1.192694,0.090356,-0.341881,-0.215924,1.053032,0.271139,1.373300,0.691195,19.02,1

In [7]:
print(int(284807*0.2))
credit_card.shape

56961

(56961, 31)

In [16]:
import random

random.randint(1, 1000)

185

In [36]:
X = credit_card.drop('Class', axis=1)
y = credit_card['Class']

amostra = X.iloc[541].values
saida = y.iloc[541]

In [37]:
amostra

array([ 4.06000000e+02, -2.31222654e+00,  1.95199201e+00, -1.60985073e+00,
        3.99790559e+00, -5.22187865e-01, -1.42654532e+00, -2.53738731e+00,
        1.39165725e+00, -2.77008928e+00, -2.77227214e+00,  3.20203321e+00,
       -2.89990739e+00, -5.95221881e-01, -4.28925378e+00,  3.89724120e-01,
       -1.14074718e+00, -2.83005567e+00, -1.68224682e-02,  4.16955705e-01,
        1.26910559e-01,  5.17232371e-01, -3.50493686e-02, -4.65211076e-01,
        3.20198199e-01,  4.45191675e-02,  1.77839798e-01,  2.61145003e-01,
       -1.43275875e-01,  0.00000000e+00])

In [38]:
saida

1

In [ ]:
amostra = [ 7.20000000e+02,  1.13092194e+00,  2.46742836e-01,  5.54944742e-01,
        9.96969328e-01, -2.29633530e-01, -2.19427652e-01, -5.99293638e-02,
        7.89747610e-02, -2.34944439e-01,  1.18616488e-01,  1.75027374e+00,
        1.10864370e+00, -1.62420873e-02,  5.51731260e-01,  5.48223501e-01,
        1.36973305e-02, -3.78144144e-01, -1.97425418e-01, -5.19323116e-01,
       -1.60240419e-01,  4.02789197e-02,  1.43724021e-01,  2.06778503e-02,
        2.07711634e-01,  4.14216279e-01, -4.39153445e-01,  3.58293605e-02,
        1.43558541e-02,  5.00000000e+00]

saida = 0

Colunas:

* Time: tempo em segundos desde a primeira transaÃ§Ã£o

* V1-V28: componentes principais obtidas com PCA

O conjunto de dados contÃ©m transaÃ§Ãµes feitas por cartÃµes de crÃ©dito em setembro de 2013 por titulares de cartÃµes europeus.

Este conjunto de dados apresenta transaÃ§Ãµes ocorridas em dois dias, onde temos 492 fraudes em 284.807 transaÃ§Ãµes. O conjunto de dados Ã© altamente desbalanceado, a classe positiva (fraudes) responde por 0,172% de todas as transaÃ§Ãµes.

A caracterÃ­stica 'Class' Ã© a variÃ¡vel de resposta e assume valor 1 em caso de fraude e 0 caso contrÃ¡rio.

In [2]:
credit_card.shape

(284807, 31)

In [2]:
print('Percentual sem fraudes', round(credit_card['Class'].value_counts()[0]/len(credit_card) * 100,3), '% do conjunto de dados')
print('Percentual com Fraudes', round(credit_card['Class'].value_counts()[1]/len(credit_card) * 100,3), '% do conjunto de dados')

Percentual sem fraudes 99.827 % do conjunto de dados
Percentual comFraudes 0.173 % do conjunto de dados

In [3]:
from imblearn.over_sampling import SMOTE
from collections import Counter

In [5]:
print('Original dataset shape %s' % Counter(y))

Original dataset shape Counter({0: 284315, 1: 492})

In [8]:
credit_card.isna().sum().sum()

0

In [9]:
credit_card_na = pd.read_csv('../dados/creditcard_na.csv')
credit_card_na.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,NaN,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,NaN,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [15]:
credit_card_na.isna().sum().sum()

7

In [ ]:
credit_card.isna().sum().sum()

In [22]:
credit_card.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [23]:
import numpy as np

In [25]:
np.mean(credit_card, axis=0)

Time      9.481386e+04
V1        3.918649e-15
V2        5.682686e-16
V3       -8.761736e-15
V4        2.811118e-15
V5       -1.552103e-15
V6        2.040130e-15
V7       -1.698953e-15
V8       -1.893285e-16
V9       -3.147640e-15
V10       1.772925e-15
V11       9.289524e-16
V12      -1.803266e-15
V13       1.674888e-15
V14       1.475621e-15
V15       3.501098e-15
V16       1.392460e-15
V17      -7.466538e-16
V18       4.258754e-16
V19       9.019919e-16
V20       5.126845e-16
V21       1.473120e-16
V22       8.042109e-16
V23       5.282512e-16
V24       4.456271e-15
V25       1.426896e-15
V26       1.701640e-15
V27      -3.662252e-16
V28      -1.217809e-16
Amount    8.834962e+01
Class     1.727486e-03
dtype: float64

In [26]:
np.zeros(credit_card.shape[1])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.allclose(np.mean(credit_card, axis=0), np.zeros(credit_card.shape[1]))

False